### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by NO-MAP** [Sailiy/vv-form-design#1]
你好，请问这个项目最后有成熟的结果出来么？

**Comment by Sailiy** [comment]
没有，公司产品改变方案，砍了。你可以参考里边的思想

**Comment by Sailiy** [comment]
你可以参考一下这个：
https://github.com/Sailiy/vue-form-making
源地址：
https://github.com/GavinZhuLei/vue-form-making
他这种实现方案虽然实现了效果，但是比较臃肿 ，不利于后期扩展组件。
我的思想采用render方式，你可以参考，后期可以动态引入组件灵活扩展。
不过由于精力有限，公司项目紧，有时间我会继续完善这个项目。

**Comment by NO-MAP** [comment]
嗯嗯，谢谢你的回复。
